### ISSUE TITLE
0.7.4 broke my CI

### ISSUE THREAD

**Issue by MShekow** [TheDoctor0/zip-release#49]
See https://github.com/focus-time/focus-time-app/pull/69

Error: `D:\a\_actions\thedoctor0\zip-release\0.7.4/entrypoint.sh: line 9: syntax error near unexpected token 'then'`

**Comment by TheDoctor0** [comment]
Thank you for reporting the issue @MShekow. I just fixed it and updated the release.

**Comment by MShekow** [comment]
Thanks for your quick response. I re-ran my CI and the problem still exists, I'm afraid.

**Comment by TheDoctor0** [comment]
Hey @MShekow. I see that in your PR the bot did not update the release, I guess just because it was the same version. I pushed a new one marked 0.7.5.

**Comment by MShekow** [comment]
Now it worked, thanks
